apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hyunjiin
resources:
  - ../../base
patches:
  - path: patch-ingress-host.yaml
  - path: patch-openapi-server-url.yaml
  - path: patch-replicas.yaml
images:
  - name: ghcr.io/tangerine-map/hyunjiin-user-api
    newName: ghcr.io/tangerine-map/hyunjiin-user-api
    newTag: 31427b8
  - name: ghcr.io/tangerine-map/hyunjiin-crawler
    newName: ghcr.io/tangerine-map/hyunjiin-crawler
    newTag: 31427b8
