apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hyunjiin
resources:
  - ../../base
patches:
  - path: patch-ingress-host.yaml
images:
  - name: ghcr.io/tangerine-map/hyunjiin-user-api
    newName: ghcr.io/tangerine-map/hyunjiin-user-api
    newTag: 640a10f
