apiVersion: v1
kind: ConfigMap
metadata:
  name: hyunjiin-user-api-config
  namespace: hyunjiin
data:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  OPENAPI_SERVER_URL: https://hyunjiin.site
