apiVersion: v1
kind: ConfigMap
metadata:
  name: hyunjiin-user-api-config
  namespace: hyunjiin
data:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  RESTAURANT_ENRICHMENT_CRAWLER_BASE_URL: http://hyunjiin-crawler:8000
