apiVersion: v1
kind: Secret
metadata:
  name: hyunjiin-user-api-secret
  namespace: hyunjiin
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql.hyunjiin.svc.cluster.local:3306/hyunjiin
  SPRING_DATASOURCE_USERNAME: hyunjiin
  SPRING_DATASOURCE_PASSWORD: change-me
