apiVersion: v1
kind: Secret
metadata:
  name: hyunjiin-user-api-secret
  namespace: hyunjiin
type: Opaque
stringData:
  spring-datasource-url: jdbc:mariadb://mariadb.hyunjiin.svc.cluster.local:3306/hyunjiin
  spring-datasource-username: root
  spring-datasource-password: password
